---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: install apache and php package
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install httpd and php package
      yum:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution in ["CentOS"]

