---
# 1. update apt and yum
- hosts: all
  become: true
  pre_tasks:
    - name: install update (CentOS)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install update (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

# 1.1 install terraform
- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_386.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

# 2. install web server, copy local html page to web server
- hosts: web_servers
  become: true
  tasks:
    - name: install httpd and php package (CentOS)
      tags: web, CentOS, httpd
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution in ["CentOS"]

    - name: install apache2 and php package (Ubuntu)
      tags: web, Ubuntu, apache2
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: start httpd (CentOS)
      tags: web, CentOS, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution in ["CentOS"]

    - name: change e-mail address for admin
      tags: web, centos, httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "CentOS"
      register: httpd

    - name: restart httpd (CentOS)
      tags: web, CentOS, httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy default html file for site
      tags: apache2, httpd, web
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0664

# 3. install mysql server
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      tags: db, mariadb, CentOS
      yum:
        name:
          - mariadb
        state: latest
      when: ansible_distribution in ["CentOS"]

    - name: install mariadb package (Ubuntu)
      tags: db, mariadb, Ubuntu
      apt:
        name:
          - mariadb-server
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

# 4. install file server
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name:
          - samba
        state: latest
